# Generated by Django 6.0.5 on 2026-05-16 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact_address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('matric_number', models.CharField(max_length=20, unique=True)),
                ('relationship_status', models.CharField(choices=[('single', 'Single'), ('in_relationship', 'In a Relationship'), ('married', 'Married'), ('prefer_not', 'Prefer Not to Say')], max_length=20)),
                ('favourite_course_mate', models.CharField(blank=True, max_length=200)),
                ('alternative_course', models.CharField(help_text='If not Computer Science, what else?', max_length=200)),
                ('favourite_programming_language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('c_cpp', 'C/C++'), ('csharp', 'C#'), ('php', 'PHP'), ('go', 'Go'), ('rust', 'Rust'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('ruby', 'Ruby'), ('other', 'Other')], max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Short bio about yourself')),
                ('quote', models.TextField(blank=True, help_text='Your favourite quote')),
                ('skills', models.TextField(blank=True, help_text='List your skills separated by commas')),
                ('image', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_class_rep', models.BooleanField(default=False)),
                ('responsibilities', models.TextField(blank=True, help_text='Class rep responsibilities')),
                ('message_to_class', models.TextField(blank=True, help_text='Message to the class')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
