# Generated by Django 6.0.5 on 2026-05-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable or disable registration manually')),
                ('opening_date', models.DateTimeField(blank=True, help_text='When registration opens', null=True)),
                ('closing_date', models.DateTimeField(blank=True, help_text='When registration closes', null=True)),
                ('message', models.TextField(blank=True, help_text='Custom message to display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Form Control',
                'verbose_name_plural': 'Form Controls',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='CPS Legacy Chronicle', max_length=200)),
                ('site_tagline', models.CharField(default='Class of 2026 - Computer Science Department', max_length=300)),
                ('department', models.CharField(default='Computer Science', max_length=200)),
                ('university', models.CharField(default='University Name', max_length=300)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='school/')),
                ('primary_color', models.CharField(default='#0A1F44', max_length=7)),
                ('accent_color', models.CharField(default='#D4AF37', max_length=7)),
                ('show_yearbook_link', models.BooleanField(default=False)),
                ('yearbook_message', models.TextField(blank=True, default='The yearbook will be available soon.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
