# Generated by Django 5.0.7 on 2026-07-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolpage',
            name='page_type',
            field=models.CharField(choices=[('vc', 'Vice Chancellor'), ('faculty', 'Faculty of Science'), ('hod', 'Head of Department'), ('ict', 'Director of ICT'), ('ippto', 'IPPTO Director')], max_length=20, unique=True),
        ),
    ]
