# Generated by Django 6.0.5 on 2026-05-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('title', models.CharField(help_text='e.g., Dr., Prof., Mr., Mrs.', max_length=100)),
                ('lecturer_type', models.CharField(choices=[('senior', 'Senior Lecturer'), ('junior', 'Junior Lecturer')], default='senior', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lecturers/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('department', models.CharField(default='Computer Science', max_length=200)),
                ('message', models.TextField(blank=True, help_text='Message or description')),
                ('specialization', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'full_name'],
            },
        ),
    ]
